### ISSUE TITLE
v1.41.7 fails to build in project - cannot find the module "stream"

### ISSUE THREAD

**Issue by connerc** [coveo/ui-kit#1616]
Greetings,

My Gridsome (Vue SSG) builds are failing because `@coveo/headless/dist/headless.esm.js` cannot find the module "stream". This has only started after updating @coveo/headless to v1.41.7.

I rolled back to v1.12.0 which is the last version I was familiar with, and my builds are successful.

```
2021-12-21T19:57:00.6838354Z Error: Cannot find module 'stream'
2021-12-21T19:57:00.6838817Z     at webpackEmptyContext (webpack:/node_modules/@coveo/headless/dist sync:2:0)
2021-12-21T19:57:00.6839677Z     at node_modules/node-fetch/lib/index.js (node_modules/@coveo/headless/dist/headless.esm.js:3691:0)
2021-12-21T19:57:00.6840312Z     at __require2 (node_modules/@coveo/headless/dist/headless.esm.js:33:0)
2021-12-21T19:57:00.6841180Z     at node_modules/cross-fetch/dist/node-ponyfill.js (node_modules/@coveo/headless/dist/headless.esm.js:4731:0)
2021-12-21T19:57:00.6841748Z     at __require2 (node_modules/@coveo/headless/dist/headless.esm.js:33:0)
2021-12-21T19:57:00.6842314Z     at Module.K95k (node_modules/@coveo/headless/dist/headless.esm.js:17472:0)
```

**Comment by olamothe** [comment]
Hello !

In that specific version, we did do an internal change to the bundler we use.

We moved from [rollup](https://rollupjs.org/) to [esbuild](https://esbuild.github.io/).

It's possible that there is a subtle difference in how they each package cross-environment packages.

In the stack trace you provided, we see it's failing when trying to resolve internal modules for `cross-fetch`, which might specify different dependencies for browser vs node environment.

Could you try to `npm i -D stream`, and see if that changes anything ?

I am also not very familiar with Vue SSG. 
This is something that runs server side, right (hybrid app) ?

In any case, we'll check if there's something we can configure in esbuild specifically for that cross platform dependency (node-fetch).

Cheers !

**Comment by samisayegh** [comment]
Hi Conner,

Indeed, the migration to esbuild adjusted how `Stream` is imported. Rollup hoisted them to the top of the file as,

```
import Stream from 'stream';
```

whereas `esbuild` keeps the original dynamic require in the distributed `node-fetch` files,

```
var Stream = _interopDefault(__require("stream"));
```

Headless still sends the requests correctly when run on a nodejs server, but in your case, I see webpack is also being used, so I'm wondering if it's playing a role?

Are you using [this option](https://gridsome.org/docs/server-api/#apiconfigurewebpackfn) in your project by any chance? If you could share minimal config (or a repo) that reproduces the issue, that would be helpful.

I'll continue investigating in the mean time,

Thanks,
Sami

**Comment by samisayegh** [comment]
I opened a branch to help test whether forcing `esbuild` to use esm imports solves the error.

Could you try it out and let us know?

Setup:
1. Clone the repo.
2. Checkout the `KIT-1308` branch.
3. Setup: `npm run setup`
4. Build: `npm run build`
5. Change dir to the headless project: `cd packages/headless`
6. Create an npm package: `npm run pack`

In your project:
1. Install the local npm package: `npm i ../...relative-path.../ui-kit/packages/headless/...tgz file`
